// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Palette } from "styling.slint";

export component FocusBorder inherits Rectangle {
    border-width: 2px;
    border-color: Palette.stroke-1-focused;

    Rectangle {
        x: parent.border-width;
        y: parent.border-width;
        width: parent.width - 2 * parent.border-width;
        height: parent.height - 2 * parent.border-width;
        border-width: 1px;
        border-radius: parent.border-width;
        border-color: Palette.stroke-2-focused;
    }
}